CREATE FUNCTION weekdays(DATE, DATE) RETURNS INTEGER AS
$$
SELECT COUNT(*)::INTEGER
FROM generate_series(LEAST($1, $2), GREATEST($1, $2), INTERVAL '1 day')
WHERE EXTRACT(DOW FROM generate_series) BETWEEN 1 AND 5
$$
LANGUAGE SQL;