SELECT
  A1.FIRST_NAME || ' ' || A1.LAST_NAME AS FIRST_ACTOR,
  A2.FIRST_NAME || ' ' || A2.LAST_NAME AS SECOND_ACTOR,
  F.TITLE
FROM
  (
    SELECT
      FA1.ACTOR_ID AS FIRST,
      FA2.ACTOR_ID AS SECOND,
      COUNT(1) AS TOTAL
    FROM
      FILM_ACTOR FA1 INNER JOIN
      FILM_ACTOR FA2 ON FA1.FILM_ID = FA2.FILM_ID
    WHERE
      FA1.ACTOR_ID <> FA2.ACTOR_ID
    GROUP BY
      FA1.ACTOR_ID,
      FA2.ACTOR_ID
    ORDER BY
      TOTAL DESC,
      FA1.ACTOR_ID
    LIMIT 1
  ) ANS INNER JOIN
  FILM_ACTOR FA1 ON ANS.FIRST = FA1.ACTOR_ID INNER JOIN
  FILM_ACTOR FA2 ON FA1.FILM_ID = FA2.FILM_ID AND ANS.SECOND = FA2.ACTOR_ID INNER JOIN
  ACTOR A1 ON ANS.FIRST = A1.ACTOR_ID INNER JOIN
  ACTOR A2 ON ANS.SECOND = A2.ACTOR_ID INNER JOIN
  FILM F ON FA1.FILM_ID = F.FILM_ID;